name: Challenges
version: 0.1
main: eu.treppi.challenges.core.ChallengesPlugin

author: treppi
api-version: 1.17

commands:
  menu:
    description: opens your menu
  timer:
    description: timer command
  spawn:
    description: teleportiert dich zum spawn
    aliases:
      - lobby
      - l
      - hub
  setspawn:
    description: setze spawn für /spawn